### ISSUE TITLE
How to blur remote video?

### ISSUE THREAD

**Issue by Apollo122** [AgoraIO/Advanced-Video#137]
We want to blur the remote video feed before showing to the user. Is this possible using MediaPreProcessing and callback? Or not how can this be archived? Could you please give us your assistance? Thank you

**Comment by plutoless** [comment]
This depends on how you wish the blur process to happen. it can happen when 1. you stream out your local video, so that everyone remotely sees your blurred video 2. you receive remote video, then you will need to apply blur on every device.
but the idea is the same, you can follow the guide here, https://docs.agora.io/en/Interactive%20Broadcast/raw_data_video_android?platform=Android
you will need to listen to onCaptureVideo callback (if you want to use approach 1), or you should use onRenderVideo callback (if you want to use approach 2). That is the chance where you can modify the raw video data.

**Comment by Apollo122** [comment]
I would like to do the second option and I know I should use onRenderVideoFrame callback but how can I blur the frame and push it to agora in a fast way?

**Comment by plutoless** [comment]
why is onRenderVideoFrame not an option for you?

**Comment by Apollo122** [comment]
@plutoless 
No that's not what I meant.
I know that I should use onCaptureVideo for approach 1 and onRenderVideo for approach 2.
The question I am asking is how can I apply blur to the frames in a fast way and call the necessary functions for agora to handle the frames?

**Comment by plutoless** [comment]
we will provide a pointer to video frame data, it's in yuv format. Agora SDK itself does not provide a function to blur your video frame, you have to do it yourself. There are lots of blur algorithms online and you may pick any or these depend on your interest. Note most algorithms are based on RGBA, so you may have to integrate libuv to convert yuv to RGBA first, blur the RGBA data, convert it back to yuv and return.

**Comment by Apollo122** [comment]
@plutoless 
from onCaptureVideoFrame I am getting these values:

byte[] data, int frameType, int width, int height, int bufferLength, int yStride, int uStride, int vStride, int rotation, long renderTimeMs

So pointer here is byte[] data right?

And after the blurring, how can I pass this blurred data to Agora?

**Comment by Apollo122** [comment]
@plutoless
I found out that manipulating data coming from the callback directly changes the frame. That good. But I couldn't find an efficient algorithm to convert yuv to RGBA and RGBA to yuv? Could you please give assistance about these functions?

**Comment by plutoless** [comment]
@Apollo122 just use libyuv. it provides all convenient functions for yuv <-> rgba conversion.

**Comment by Apollo122** [comment]
Thanks. We ended up using a method blurs yuv data directly.
