### ISSUE TITLE
handle voip push notification for calling 

### ISSUE THREAD

**Issue by PrashantKT** [AgoraIO/Advanced-Video#47]
I am trying to join a  channel  when voip push received using apple pushkit. and then I try to create data stream to send and receive the status message like call ringing, call connected , call disconnected   but some time data stream work and some time not,  

Could you please provide any other alternative that Can i used to pass the status or string ?. If not then what should I do to use data stream efficiently. 

**When App is killed and device is  locked and push received 9 out of 10 cases stream message not received other side**   

**When App is killed but device  not locked  and push received 2-3 out of 10 cases stream message not received other side**   

It is very important feature and we can't compromise with this. If you could help will be helpful.

**Comment by PrashantKT** [comment]
Uploaded my channel manager 

[AgoraCallChannelManager.txt](https://github.com/AgoraIO/Advanced-Video/files/3166745/AgoraCallChannelManager.txt)

**Comment by plutoless** [comment]
@PrashantKT the data stream goes with video stream which is sent via udp, so it's true it can be lost. The issue you described partially it's because of device limitation (the video stream is cut or reduced priority when going to backend or lock screen), on the other hand, if you wish to have sth stable for signaling service, it's recommended to use a standard signaling SDK instead of using our data stream api. If you really want to use it, maybe you can send redundant pacakges and remove duplication in receiver side.
Hope this helps.

**Comment by PrashantKT** [comment]
Okay thanks updated with Singling sdk
