### ISSUE TITLE
Gradle Build and Java Class Question

### ISSUE THREAD

**Issue by ArcherEmiya05** [AgoraIO/Advanced-Video#64]
#### Question 1:
What exactly this library do with the issue #73. What is the issue I can't find it.

```
implementation('com.github.tony19:logback-android-classic:1.1.1-4') {
        // workaround issue #73
        exclude group: 'com.google.android', module: 'android'
    }
```
#### Question 2:
Is this line really required because it showing an error/warning with "Device support but APK only support armeabi-v7a, x86

```
ndk {
            abiFilters "armeabi-v7a", "x86" // DO NOT MODIFY THIS LINE, IT'S UPDATED BY BUILD MACHINE AUTOMATICALLY.
        }
```
I do understand that this is for 32-bit devices. Is there any conflict in building and running the app? Like a 32-bit device may get a 64-bit app by accident?

#### Question 3:
Does `RecyclerViewNoBugLinearLayoutManager.class` still need today with AndroidX? This is from `LargeGroupVideoChat` sample for Android.

By the way I'm starting to love Agora. Great samples, APIs, dashboard, and documentation should definitely recommend this to anyone.

**Comment by brianxcli** [comment]
#### Question 1 #### 

The issue #73 came from the previous repo, so just ignore the number. We will take a look at it and update the comment.

#### Question 2 ####

The line is not actually optional, because our SDK supports only v7a, v8a and X86 architectures, with X86_64 coming soon. 

We recommend that you add "arm64-v8a" to the ABI list if you want explicitly to support arm64, while v7a libraries will be running on a 64-bit device properly if other libraries you are using don't conflict. On the contrary, an arm64 library cannot be loaded on a device that only supports 32-bit, but there being nearly no such Android mobile device in use right now.

#### Question 3 ####
I think such class will not be necessary at the moment. 
  
Thanks for your love in Agora.

**Comment by ArcherEmiya05** [comment]
Great! So regarding question 1 can I remove this library? How about in question 2, as I recall PlayStore will soon phase out 32 bit app so what are my option?

**Comment by brianxcli** [comment]
Question 1: It's your decision whether to use any third-party logging or some other libraries.

Question 2: If you wanna upload products to play store, it's more recommended to package apps using bundle right now. You will not concern in architectures if you've already declared the use of 64-bit and provided the 64-bit libraries. The packaging tools will help you filter out those not used.

**Comment by ArcherEmiya05** [comment]
> Question 2: If you wanna upload products to play store, it's more recommended to package apps using bundle right now. You will not concern in architectures if you've already declared the use of 64-bit and provided the 64-bit libraries. The packaging tools will help you filter out those not used.

So this means that I can freely remove the `abiFilters` if I generate a Bundle (aab)?

**Comment by brianxcli** [comment]
I am not sure about that yet. But why do you care this so much.

**Comment by plutoless** [comment]
@ArcherEmiya05 is there any specific reasons that you want to take this out? It should leave you no harm if you keep it i guess?

**Comment by ArcherEmiya05** [comment]
It doesn't allow me to install the app with usb debugging with `abiFilters `, but I will try to restart the IDE and device as well and try it again.

**Comment by brianxcli** [comment]
If you're debugging your app through Gradle builds, there shouldn't be any problem, since we are doing this all day.

I haven't tried app bundle, but if it indeed troubles you, you can add arm64-v8a to the list or just try to remove the abi list. Meanwhile I'll do some tests on it.

**Comment by ArcherEmiya05** [comment]
![image](https://user-images.githubusercontent.com/38008900/60884401-5b6e1c80-a27f-11e9-9a95-7fe1d39d4b1c.png)


This is what it looks like when publishing the app to PlayStore.

**Comment by plutoless** [comment]
see above answer for question 2 to get rid of this warning,
If you wanna upload products to play store, it's more recommended to package apps using bundle right now. You will not concern in architectures if you've already declared the use of 64-bit and provided the 64-bit libraries. The packaging tools will help you filter out those not used.

**Comment by brianxcli** [comment]
> This is what it looks like when publishing the app to PlayStore.
How have you configured the project to get to this warning?

**Comment by brianxcli** [comment]
It's likely that you choose only to support 32-bit libraries without the 64-bit equivalences.
In our case, that means you've declared ABIs v7a or X86, but not v8a or X86_64. 
Since agora doesn't provide X86_64 libraries, you may have to decide not to add X86 to your ABI list.
That should solve your problem.
